export enum Player {
    Ameng = 'Ameng',
    Apr1ta = 'Apr1ta',
    Coldest = 'Coldest',
    Diya = 'Diya',
    Eileen = 'Eileen',
    Farway1987 = 'Farway1987',
    GA9A = 'GA9A',
    Jimmy = 'Jimmy',
    JinMu = 'JinMu',
    Kaneki = 'Kaneki',
    Kyo = 'Kyo',
    Lengsa = 'Lengsa',
    MinSea = 'MinSea',
    MoLanran = 'MoLanran',
    Molly = 'Molly',
    Nisha = 'Nisha',
    Pineapple = 'Pineapple',
    ShowCheng = 'ShowCheng',
    Superich = 'Superich',
    TBD = 'TBD',
}
