const PropList = {
    library: ['playlists', 'updatedAt'],
    playlist: [
        'id',
        'name',
        'description',
        'creator',
        'category',
        'coverImgUrl',
        'tinyCoverImgUrl',
        'releaseDate',
        'songs',
        'updatedAt',
    ],
    playlistSong: [
        'id',
        'name',
        'artist',
        'album',
        'duration',
        'tinyAlbumImgUrl',
        'featured',
    ],
    playlistItem: ['id', 'name', 'category', 'tinyCoverImgUrl'],
    songLibrary: ['songs', 'updatedAt'],
    song: [
        'id',
        'name',
        'artist',
        'album',
        'duration',
        'albumImgUrl',
        'tinyAlbumImgUrl',
        'playlistIds',
        'resources',
        'lyrics',
        'theme',
        'updatedAt',
    ],
    songResource: ['label', 'path'],
    config: ['version', 'resourcePrefix'],
};

module.exports = PropList;
