export enum MixBlendMode {
    Normal = 'normal',
    Multiply = 'multiply',
    Screen = 'screen',
    Overlay = 'overlay',
    Darken = 'darken',
    Lighten = 'lighten',
    ColorDodge = 'color-dodge',
    ColorBurn = 'color-burn',
    HardLight = 'hard-light',
    SoftLight = 'soft-light',
    Difference = 'difference',
    Exclusion = 'exclusion',
    Hue = 'hue',
    Saturation = 'saturation',
    Color = 'color',
    Luminosity = 'luminosity',
}

export enum ThemeColor {
    Red = 'red',
    Orange = 'orange',
    Yellow = 'yellow',
    Green = 'green',
    Cyan = 'cyan',
    Blue = 'blue',
    Purple = 'purple',
    Pink = 'pink',
    Gray = 'gray',
    Black = 'black',
    White = 'white',
}
