export const LINKS_DATA = [
    {
        name: '哔哩哔哩',
        description: 'bilibili',
        image: 'https://tse1-mm.cn.bing.net/th/id/OIP-C.gBc7pn6xuHfIxzSmhzGdRAHaEK?pid=ImgDet&rs=1',
        primary: '#fff',
        secondary: '#00a1d6',
        link: 'https://www.bilibili.com/',
    },
    {
        name: 'OWL',
        description: '守望先锋联赛',
        image: 'https://tvax3.sinaimg.cn/crop.0.0.400.400.180/006Z6gayly8gjx1i04ftlj30b40b4t9v.jpg?KID=imgbed,tva&Expires=1661465628&ssig=xO2%2BUX6BwL',
        primary: '#fff',
        secondary: '#f79e16',
        link: 'https://live.bilibili.com/76',
    },
    {
        name: '斗鱼',
        description: 'douyu',
        image: 'https://tvax1.sinaimg.cn/crop.65.55.288.288.180/ed639409ly8gdino1e5eyj20b40b474j.jpg?KID=imgbed,tva&Expires=1661460700&ssig=5cNhEw%2FMCQ',
        primary: '#fe552e',
        secondary: '#f7c100',
        link: 'https://www.douyu.com/',
    },
    {
        name: '微博',
        description: 'weibo',
        image: 'https://ww2.sinaimg.cn/mw2000/61ecce97jw9e2suzathlqj.jpg',
        primary: '#fff',
        secondary: '#fed442',
        link: 'https://weibo.com/hot/search',
    },
    {
        name: '知乎',
        description: 'zhihu',
        image: 'https://pic1.zhimg.com/v2-abed1a8c04700ba7d72b45195223e0ff_is.jpeg',
        primary: '#64b6e8',
        secondary: '#0461cf',
        link: 'https://www.zhihu.com/',
    },
    {
        name: '掘金',
        description: 'juejin',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.300.300.180/005SiNxyly1grmfsioj9sj308c08c3yc.jpg?KID=imgbed,tva&Expires=1661463801&ssig=kuIOYWBoT3',
        primary: '#1e80ff',
        secondary: '#1e61ff',
        link: 'https://juejin.cn/',
    },
    {
        name: '谷歌翻译',
        description: 'google',
        image: 'https://ssl.gstatic.com/translate/favicon.ico',
        primary: '#fff',
        secondary: '#4c8bf5',
        link: 'https://translate.google.cn/',
    },
    {
        name: 'MDN',
        description: 'mozilla',
        image: 'https://developer.mozilla.org/favicon-192x192.png',
        primary: '#15141a',
        secondary: '#524e66',
        link: 'https://developer.mozilla.org/zh-CN/',
    },
    {
        name: 'GitHub',
        description: 'github',
        image: 'https://github.githubassets.com/apple-touch-icon-144x144.png',
        primary: '#231f20',
        secondary: '#6f6265',
        link: 'https://github.com/',
    },
    {
        name: 'TypeScript',
        description: 'typescriptlang',
        image: 'https://www.typescriptlang.org/icons/icon-144x144.png?v=8944a05a8b601855de116c8a56d3b3ae',
        primary: '#3178c6',
        secondary: '#3f9aff',
        link: 'https://www.typescriptlang.org/docs/handbook/2/basic-types.html',
    },
    {
        name: 'React',
        description: 'reactjs',
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K',
        primary: '#20232a',
        secondary: '#50b5d1',
        link: 'https://zh-hans.reactjs.org/',
    },
    {
        name: 'Vue',
        description: 'vuejs',
        image: 'https://cn.vuejs.org/logo.svg',
        primary: '#fff',
        secondary: '#42b883',
        link: 'https://cn.vuejs.org/',
    },
    {
        name: 'Tailwind',
        description: 'tailwindcss',
        image: 'https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/tailwind-css-icon.png',
        primary: '#e5f3fc',
        secondary: '#38bdf8',
        link: 'https://tailwindcss.com/docs/installation',
    },
    {
        name: 'Swift',
        description: 'swift',
        image: 'https://developer.apple.com/swift/images/swift-logo.svg',
        primary: '#f05138',
        secondary: '#65190f',
        link: 'https://www.swift.org/',
    },
    {
        name: 'Apple',
        description: 'apple',
        image: 'https://developer.apple.com/assets/elements/icons/brandmark/apple-developer-brandmark.svg',
        primary: '#fff',
        secondary: '#000',
        link: 'https://developer.apple.com/',
    },
    {
        name: 'Unsplash',
        description: 'unsplash',
        image: 'https://unsplash.com/android-chrome-192x192.png',
        primary: '#fff',
        secondary: '#000',
        link: 'https://unsplash.com/@talaxy',
    },
    {
        name: '阿里云',
        description: 'aliyun',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.1080.1080.180/620c4763ly8gdks9658z4j20u00u0js0.jpg?KID=imgbed,tva&Expires=1661466527&ssig=3OiKKshqOb',
        primary: '#fd6800',
        secondary: '#ff791a',
        link: 'https://www.aliyun.com/',
    },
    {
        name: '腾讯云',
        description: 'tencent',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.512.512.180/005EbuQTly8h0pnakqaizj30e80e8dfy.jpg?KID=imgbed,tva&Expires=1661466580&ssig=VCkuM%2Bi72w',
        primary: '#fff',
        secondary: '#0354da',
        link: 'https://cloud.tencent.com/',
    },
    {
        name: '网易云音乐',
        description: 'netease',
        image: 'https://wx1.sinaimg.cn/mw2000/6694d955ly1g8n8hdn9jzj20b40b4wez.jpg',
        primary: '#dc001a',
        secondary: '#a90013',
        link: 'https://music.163.com/',
    },
    {
        name: 'QQ音乐',
        description: 'tencent',
        image: 'https://tvax3.sinaimg.cn/crop.0.0.640.640.180/814a4ae9ly8gditt8dsk5j20hs0hsq3k.jpg?KID=imgbed,tva&Expires=1661466160&ssig=nju%2FcZnwRd',
        primary: '#fff',
        secondary: '#31c27c',
        link: 'https://y.qq.com/',
    },
    {
        name: '暴雪战网',
        description: 'battlenet',
        image: 'https://tvax4.sinaimg.cn/crop.0.0.828.828.180/006q8RPdly8gdi6ife9bbj30n00n0t9m.jpg?KID=imgbed,tva&Expires=1661465508&ssig=XJEmQMpU%2FK',
        primary: '#010101',
        secondary: '#00b3e7',
        link: 'https://www.blizzardgames.cn/zh-cn/',
    },
];

const empty = {
    name: '',
    description: '',
    image: '',
    primary: '#',
    secondary: '#',
    link: '',
};