export const LINKS_DATA = [
    {
        name: 'MDN',
        description: 'mozilla',
        image: 'https://developer.mozilla.org/favicon-192x192.png',
        primary: '#15141a',
        secondary: '#524e66',
        link: 'https://developer.mozilla.org/zh-CN/',
    },
    {
        name: 'GitHub',
        description: 'github',
        image: 'https://github.githubassets.com/apple-touch-icon-144x144.png',
        primary: '#231f20',
        secondary: '#6f6265',
        link: 'https://github.com/',
    },
    {
        name: '谷歌翻译',
        description: 'google',
        image: 'https://ssl.gstatic.com/translate/favicon.ico',
        primary: '#fff',
        secondary: '#4c8bf5',
        link: 'https://translate.google.cn/',
    },
    {
        name: 'TypeScript',
        description: 'typescriptlang',
        image: 'https://www.typescriptlang.org/icons/icon-144x144.png?v=8944a05a8b601855de116c8a56d3b3ae',
        primary: '#3178c6',
        secondary: '#3f9aff',
        link: '',
    },
    {
        name: 'React',
        description: 'reactjs',
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K',
        primary: '#20232a',
        secondary: '#50b5d1',
        link: 'https://zh-hans.reactjs.org/',
    },
    {
        name: 'Vue',
        description: 'vuejs',
        image: 'https://cn.vuejs.org/logo.svg',
        primary: '#fff',
        secondary: '#42b883',
        link: 'https://cn.vuejs.org/',
    },
    {
        name: 'Swift',
        description: 'swift',
        image: 'https://developer.apple.com/swift/images/swift-logo.svg',
        primary: '#f05138',
        secondary: '#65190f',
        link: 'https://www.swift.org/',
    },
    {
        name: 'Apple',
        description: 'developer',
        image: 'https://developer.apple.com/assets/elements/icons/brandmark/apple-developer-brandmark.svg',
        primary: '#fff',
        secondary: '#000',
        link: 'https://developer.apple.com/',
    },
    {
        name: '掘金',
        description: 'juejin',
        image: 'https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/6c61ae65d1c41ae8221a670fa32d05aa.svg',
        primary: '#fff',
        secondary: '#1e80ff',
        link: 'https://juejin.cn/',
    },
    {
        name: '哔哩哔哩',
        description: 'bilibili',
        image: 'https://tse1-mm.cn.bing.net/th/id/OIP-C.gBc7pn6xuHfIxzSmhzGdRAHaEK?pid=ImgDet&rs=1',
        primary: '#fff',
        secondary: '#00a1d6',
        link: '',
    }
];

const empty = {
    name: '',
    description: '',
    image: '',
    primary: '#',
    secondary: '#',
    link: '',
};