export const LINKS_DATA = [
    {
        name: '哔哩哔哩',
        description: 'bilibili',
        image: 'https://tvax4.sinaimg.cn/crop.0.0.1024.1024.180/001UiKmJly8h0pdqge7b1j60sg0sh3z502.jpg?KID=imgbed,tva&Expires=1664702963&ssig=os%2F%2FK7%2BfIX',
        primary: '#fff',
        secondary: '#00b1fd',
        link: 'https://www.bilibili.com/',
    },
    {
        name: '斗鱼',
        description: 'douyu',
        image: 'https://tvax1.sinaimg.cn/crop.65.55.288.288.180/ed639409ly8gdino1e5eyj20b40b474j.jpg?KID=imgbed,tva&Expires=1661460700&ssig=5cNhEw%2FMCQ',
        primary: '#fe552e',
        secondary: '#cb4324',
        link: 'https://www.douyu.com/',
    },
    {
        name: '微博',
        description: 'weibo',
        image: 'https://www.leigod.com/img/weibo.png',
        primary: '#fed442',
        secondary: '#e32529',
        link: 'https://weibo.com/hot/search',
    },
    {
        name: '知乎',
        description: 'zhihu',
        image: 'https://pic1.zhimg.com/v2-abed1a8c04700ba7d72b45195223e0ff_is.jpeg',
        primary: '#64b6e8',
        secondary: '#0461cf',
        link: 'https://www.zhihu.com/',
    },
    {
        name: '掘金',
        description: 'juejin',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.300.300.180/005SiNxyly1grmfsioj9sj308c08c3yc.jpg?KID=imgbed,tva&Expires=1661463801&ssig=kuIOYWBoT3',
        primary: '#1e80ff',
        secondary: '#1e61ff',
        link: 'https://juejin.cn/',
    },
    {
        name: 'MDN',
        description: 'mozilla',
        image: 'https://r.photo.store.qq.com/psc?/V53zNsw50AU6SY3IaO3s4AEy7E1ioe76/bqQfVz5yrrGYSXMvKr.cqcift1TOEugeo6dTQHAJfrwzIRG4eOOzgf.*HTXm8ZpHHnE9Ci6nR68BvTCTYK9qVNV3XhxuZZr0hFHrZlM8ufk!/r',
        primary: '#15141a',
        secondary: '#524e66',
        link: 'https://developer.mozilla.org/zh-CN/',
    },
    {
        name: 'GitHub',
        description: 'github',
        image: 'https://r.photo.store.qq.com/psc?/V53zNsw50AU6SY3IaO3s4AEy7E1ioe76/bqQfVz5yrrGYSXMvKr.cqVcsalJAj.tDlaBZVYKOJBwjKjwcwyR*tvvJQw8FcCY4A2W0I0*fRKsEvkHiiecet7Gak1OEjmI0yCZAJIr7sMA!/r',
        primary: '#231f20',
        secondary: '#6f6265',
        link: 'https://github.com/',
    },
    {
        name: 'TypeScript',
        description: 'typescriptlang',
        image: '/logo/typescript.svg',
        primary: '#3178c6',
        secondary: '#3f9aff',
        link: 'https://www.typescriptlang.org/docs/handbook/2/basic-types.html',
    },
    {
        name: 'React',
        description: 'meta',
        image: '/logo/react.svg',
        primary: '#20232a',
        secondary: '#50b5d1',
        link: 'https://zh-hans.reactjs.org/',
    },
    {
        name: 'Next.js',
        description: 'vercel',
        image: '/logo/next-js.svg',
        primary: '#fff',
        secondary: '#4c4c4c',
        link: 'https://docusaurus.io/docs',
    },
    {
        name: 'Vue',
        description: 'vuejs',
        image: '/logo/vue-js.svg',
        primary: '#fff',
        secondary: '#42b883',
        link: 'https://cn.vuejs.org/',
    },
    {
        name: 'Vite',
        description: 'vitejs',
        image: '/logo/vite-js.svg',
        primary: '#242424',
        secondary: '#646cff',
        link: 'https://cn.vitejs.dev/',
    },
    {
        name: 'Tailwind',
        description: 'tailwindcss',
        image: '/logo/tailwindcss.svg',
        primary: '#e5f3fc',
        secondary: '#38bdf8',
        link: 'https://tailwindcss.com/docs/installation',
    },
    {
        name: 'Docusaurus',
        description: 'meta',
        image: '/logo/docusaurus.svg',
        primary: '#e6f6e6',
        secondary: '#18816a',
        link: 'https://docusaurus.io/docs',
    },
    {
        name: 'Can I use',
        description: 'caniuse',
        image: 'https://caniuse.com/img/favicon-128.png',
        primary: '#f2e8d4',
        secondary: '#b6afa0',
        link: 'https://caniuse.com/',
    },
    {
        name: 'Swift',
        description: 'swift',
        image: '/logo/swift.svg',
        primary: '#f05138',
        secondary: '#65190f',
        link: 'https://www.swift.org/',
    },
    {
        name: 'Apple',
        description: 'apple',
        image: '/logo/apple-developer.svg',
        primary: '#fff',
        secondary: '#000',
        link: 'https://developer.apple.com/',
    },
    {
        name: 'Unsplash',
        description: 'unsplash',
        image: 'https://unsplash.com/android-chrome-192x192.png',
        primary: '#fff',
        secondary: '#000',
        link: 'https://unsplash.com/@talaxy',
    },
    {
        name: '阿里云',
        description: 'aliyun',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.1080.1080.180/620c4763ly8gdks9658z4j20u00u0js0.jpg?KID=imgbed,tva&Expires=1661466527&ssig=3OiKKshqOb',
        primary: '#fd6800',
        secondary: '#ff791a',
        link: 'https://www.aliyun.com/',
    },
    {
        name: '腾讯云',
        description: 'tencent',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.512.512.180/005EbuQTly8h0pnakqaizj30e80e8dfy.jpg?KID=imgbed,tva&Expires=1661466580&ssig=VCkuM%2Bi72w',
        primary: '#fff',
        secondary: '#0354da',
        link: 'https://cloud.tencent.com/',
    },
    {
        name: '有道翻译',
        description: 'netease',
        image: 'https://shared.ydstatic.com/fanyi/fanyi-ad-place/online/0.0.11/images/logo_cidian.png',
        primary: '#fc011a',
        secondary: '#e00012',
        link: 'https://fanyi.youdao.com/',
    },
    {
        name: '谷歌翻译',
        description: 'google',
        image: 'https://ssl.gstatic.com/translate/favicon.ico',
        primary: '#fff',
        secondary: '#4c8bf5',
        link: 'https://translate.google.cn/',
    },
    {
        name: '网易云音乐',
        description: 'netease',
        image: 'https://tvax1.sinaimg.cn/crop.0.0.400.400.180/001StgMtly8h0oxyk0mspj60b40b4t8o02.jpg?KID=imgbed,tva&Expires=1661527462&ssig=4LGFnzT9KN',
        primary: '#dc001a',
        secondary: '#a90013',
        link: 'https://music.163.com/',
    },
    {
        name: 'QQ音乐',
        description: 'tencent',
        image: 'https://tvax3.sinaimg.cn/crop.0.0.640.640.180/814a4ae9ly8gditt8dsk5j20hs0hsq3k.jpg?KID=imgbed,tva&Expires=1661466160&ssig=nju%2FcZnwRd',
        primary: '#fff',
        secondary: '#31c27c',
        link: 'https://y.qq.com/',
    },
    {
        name: '高德地图',
        description: 'amap',
        image: 'https://tvax2.sinaimg.cn/crop.0.0.511.511.180/001Oq62Bly8guu1ai1il6j60e70e83yn02.jpg?KID=imgbed,tva&Expires=1661528496&ssig=2NFh1caSZs',
        primary: '#eaf2f2',
        secondary: '#0085fe',
        link: 'https://www.amap.com/',
    },
    {
        name: '暴雪战网',
        description: 'battlenet',
        image: 'https://tvax4.sinaimg.cn/crop.0.0.828.828.180/006q8RPdly8gdi6ife9bbj30n00n0t9m.jpg?KID=imgbed,tva&Expires=1661465508&ssig=XJEmQMpU%2FK',
        primary: '#010101',
        secondary: '#00b3e7',
        link: 'https://www.blizzardgames.cn/zh-cn/',
    },
];

export const EXTRA_LINKS = [
    {
        name: '我的 UA',
        link: 'https://www.bestproxyreviews.com/user-agent/',
    },
];

const empty = {
    name: '',
    description: '',
    image: '',
    primary: '#',
    secondary: '#',
    link: '',
};
