export enum Hero {
    DVA = 'D.VA',
    DoomFist = '末日铁拳',
    JunkerQueen = '渣克女王',
    Orisa = '奥丽莎',
    Reinhardt = '莱因哈特',
    RoadHog = '路霸',
    Sigma = '西格玛',
    Winston = '温斯顿',
    WreckingBall = '破坏球',
    Zarya = '查理娅',
    Ashe = '艾什',
    Bastion = '堡垒',
    Cassidy = '卡西迪',
    Echo = '回声',
    Genji = '源氏',
    Hanzo = '半藏',
    Junkrat = '狂鼠',
    Mei = '美',
    Pharah = '法老之鹰',
    Reaper = '死神',
    Sojourn = '索杰恩',
    Soldier = '士兵：76',
    Sombra = '黑影',
    Symmetra = '秩序之光',
    Torbjorn = '托比昂',
    Tracer = '猎空',
    WidowMaker = '黑百合',
    Ana = '安娜',
    Baptiste = '巴蒂斯特',
    Brigitte = '布里吉塔',
    Kiriko = '雾子',
    Lucio = '卢西奥',
    Mercy = '天使',
    Moira = '莫伊拉',
    Zenyatta = '禅雅塔',
    TBD = '',
}

export const HERO_DATA = {
    [Hero.DVA]: { name: 'D.VA', color: '#f79fca' },
    [Hero.DoomFist]: { name: '末日铁拳', color: '#968386' },
    [Hero.JunkerQueen]: { name: '渣克女王', color: '#8cb4d7' },
    [Hero.Orisa]: { name: '奥丽莎', color: '#79997f' },
    [Hero.Reinhardt]: { name: '莱因哈特', color: '#9ea9ac' },
    [Hero.RoadHog]: { name: '路霸', color: '#bd9a82' },
    [Hero.Sigma]: { name: '西格玛', color: '#9ea9ac' },
    [Hero.Winston]: { name: '温斯顿', color: '#a9adc1' },
    [Hero.WreckingBall]: { name: '破坏球', color: '#e29e7f' },
    [Hero.Zarya]: { name: '查理娅', color: '#f391bc' },
    [Hero.Ashe]: { name: '艾什', color: '#838487' },
    [Hero.Bastion]: { name: '堡垒', color: '#8d9b8e' },
    [Hero.Cassidy]: { name: '卡西迪', color: '#b88082' },
    [Hero.Echo]: { name: '回声', color: '#a5d0fb' },
    [Hero.Genji]: { name: '源氏', color: '#a1f77f' },
    [Hero.Hanzo]: { name: '半藏', color: '#bfba98' },
    [Hero.Junkrat]: { name: '狂鼠', color: '#f2c180' },
    [Hero.Mei]: { name: '美', color: '#84b1f0' },
    [Hero.Pharah]: { name: '法老之鹰', color: '#788dca' },
    [Hero.Reaper]: { name: '死神', color: '#8e7b80' },
    [Hero.Sojourn]: { name: '索杰恩', color: '#d98583' },
    [Hero.Soldier]: { name: '士兵：76', color: '#848a9e' },
    [Hero.Sombra]: { name: '黑影', color: '#897fbd' },
    [Hero.Symmetra]: { name: '秩序之光', color: '#897fbd' },
    [Hero.Torbjorn]: { name: '托比昂', color: '#c58989' },
    [Hero.Tracer]: { name: '猎空', color: '#dfa07f' },
    [Hero.WidowMaker]: { name: '黑百合', color: '#a785ad' },
    [Hero.Ana]: { name: '安娜', color: '#8697b7' },
    [Hero.Baptiste]: { name: '巴蒂斯特', color: '#7db9ce' },
    [Hero.Brigitte]: { name: '布里吉塔', color: '#998384' },
    [Hero.Kiriko]: { name: '雾子', color: '#e1bdec' },
    [Hero.Lucio]: { name: '卢西奥', color: '#93ce82' },
    [Hero.Mercy]: { name: '天使', color: '#f5f0c0' },
    [Hero.Moira]: { name: '莫伊拉', color: '#a089e7' },
    [Hero.Zenyatta]: { name: '禅雅塔', color: '#f6ed91' },
};
