export enum Player {
    Ameng = 'Ameng',
    Coldest = 'Coldest',
    Diya = 'Diya',
    Eileen = 'Eileen',
    Farway1987 = 'Farway1987',
    GA9A = 'GA9A',
    Jimmy = 'Jimmy',
    JinMu = 'JinMu',
    Kaneki = 'Kaneki',
    Kyo = 'Kyo',
    Lengsa = 'Lengsa',
    MinSea = 'MinSea',
    MoLanran = 'MoLanran',
    ShowCheng = 'ShowCheng',
}
